<?php

include_once get_path('utils', 'types_utils/sinistre.php');

try {
    $sinistre = new Sinistre(array(
        'contract' => 'dskfghsdlqk',
        'user' => 'fhdskql',
        'user_profession' => 'esclave',
        'driver_profession' => 'portier',
        'driver_relationship' => 'married',
        'driver_user_same_residance' => false,
        'driver_is_usual' => false,
        'driver_is_employeeof_user' => false,
        'driver_disp_reason' => 'work',
        'circumstances' => 'i don\'t know',
        'proces_verbal' => false,
        'police_report' => false,
        'main_courrante' => false,
        'police_station' => 'salut',
        'usual_parking_location' => 'chez moi',
        'injureds' => array(
            array(
                'firstname' => 'salut',
                'lastname' => 'c\'est moi',
                'address' => 'jsp',
                'phone' => '+3305839123',
                'profession' => 'truc',
                'belt' => true,
                'injuries' => 'dead x(',
            ),
        ),
        'constat' => array(
            'date' => 0,
            'location' => 'fdhgd',
            'injured' => true,
            'other_vehicle_involved' => true,
            'other_object_involved' => true,
            'wintensses' => 'salut',
            'vehicle_A' => array(
                'user' => 'fdghjfgekerz',
                'contract' => 'fhekgezyrte',
                'assurance' => 'feklfgrefyre',
                'driver_firstname' => 'a',
                'driver_lastname' => 'b',
                'driver_birthdate' => 0,
                'driver_address' => 'jsp',
                'driver_country' => 'russie',
                'driver_phone' => '+3305658502',
                'dirver_email' => 'a@b.com',
                'driver_liscence_id' => 'FDFHgfeiur',
                'driver_liscence_cat' => 'fjlmre',
                'driver_liscence_expire' => 0,
                'vehicle_initial_impact' => 'sfdgs',
                'vehicle_damage' => 'sgfdsreqsdf',
                'observation' => 'xdfgs',
                'stationing' => true,
                'leaving_parking_spot' => false,
                'entering_parking_spot' => false,
                'entering_place' => false,
                'leaving_place' => false,
                'round_point' => false,
                'rear_damage_on_road' => false,
                'oposite_road_line' => false,
                'line_change' => false,
                'overtake' => false,
                'right_turn' => false,
                'left_turn' => false,
                'driving_backward' => false,
                'past_line' => false,
                'from_right' => false,
                'skip_priority' => false,
            ),
            'vehicle_B' => array(
                'user' => 'fdghjfgekerz',
                'contract' => 'fhekgezyrte',
                'assurance' => 'feklfgrefyre',
                'driver_firstname' => 'a',
                'driver_lastname' => 'b',
                'driver_birthdate' => 0,
                'driver_address' => 'jsp',
                'driver_country' => 'russie',
                'driver_phone' => '+3305658502',
                'dirver_email' => 'a@b.com',
                'driver_liscence_id' => 'FDFHgfeiur',
                'driver_liscence_cat' => 'fjlmre',
                'driver_liscence_expire' => 0,
                'vehicle_initial_impact' => 'sfdgs',
                'vehicle_damage' => 'sgfdsreqsdf',
                'observation' => 'xdfgs',
                'stationing' => true,
                'leaving_parking_spot' => false,
                'entering_parking_spot' => false,
                'entering_place' => false,
                'leaving_place' => false,
                'round_point' => false,
                'rear_damage_on_road' => false,
                'oposite_road_line' => false,
                'line_change' => false,
                'overtake' => false,
                'right_turn' => false,
                'left_turn' => false,
                'driving_backward' => false,
                'past_line' => false,
                'from_right' => false,
                'skip_priority' => false,
            ), ),
    ));
} catch (Exception $e) {
    echo $e->getMessage();
}

?>
